DROP TABLE IF EXISTS access_log;

CREATE TABLE access_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  access_date TEXT NOT NULL,
  image_url TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);